version: '3.2'
services:
  gdc-web:
    image: gdc-website
    build:
      context: .         
      dockerfile: Dockerfile
    container_name: gdc_website_container
    ports:
      - "80:5173"      
    volumes:
      - app_data:/app
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=gdc.mec.ac.in

volumes:
  app_data:

