
services:
  web:
    image: gdc-website
    build:
      context: .         
      dockerfile: Dockerfile
    container_name: gdc_website_container
    ports:
      - "5173:5173"      
    volumes:
      - .:/app           
    environment:
      - NODE_ENV=production 
