const pastEvents = {
  'MEC': [
    {
      title: 'Unity Workshop',
      college: 'MEC',
      venuep1: 'CCF',
      venuep2: 'HALL',
      date: '12/07/22',
      detail:
        'We host a variety of events, including seminars, game jams, competitions, and guest lectures to promote learning and creativity. The club also provides chances to promote and publish games, connect with other game makers, and learn useful industry insights',
      image: 'https://rare-gallery.com/thumbnail/394521-valorant-game-agents-hero-4k-pc-wallpaper.jpg',
      status: 'View Report',
    },
    {
      title: 'Game Jam',
      college: 'MEC',
      venuep1: 'SDPK',
      venuep2: 'LAB',
      date: '20/07/22',
      detail: 'A competition where participants had to create a game prototype in a short period of time.',
      image: 'https://rare-gallery.com/thumbnail/394522-gaming-game-jam.jpg',
      status: 'View Report',
    },
  ],

  'MES Engineering College': [
    {
      title: 'VR Seminar',
      college: 'MES Engineering College',
      venuep1: 'MAIN',
      venuep2: 'HALL',
      date: '14/07/22',
      detail: 'Seminar on the future of virtual reality and its applications in gaming.',
      image: 'https://rare-gallery.com/thumbnail/394523-vr-gaming.jpg',
      status: 'View Report',
    },
    {
      title: 'AI in Games Workshop',
      college: 'MES Engineering College',
      venuep1: 'LAB',
      venuep2: '3',
      date: '18/07/22',
      detail: 'A hands-on workshop on implementing AI for NPC behavior in games.',
      image: 'https://rare-gallery.com/thumbnail/394524-ai-gaming.jpg',
      status: 'View Report',
    },
  ],
  'Illahia College of Engineering': [
    {
      title: 'VR Seminar',
      college: 'Illahia College of Engineering',
      venuep1: 'MAIN',
      venuep2: 'HALL',
      date: '14/07/22',
      detail: 'Seminar on the future of virtual reality and its applications in gaming.',
      image: 'https://rare-gallery.com/thumbnail/394523-vr-gaming.jpg',
      status: 'View Report',
    },
    {
      title: 'AI in Games Workshop',
      college: 'Illahia College of Engineering',
      venuep1: 'LAB',
      venuep2: '3',
      date: '18/07/22',
      detail: 'A hands-on workshop on implementing AI for NPC behavior in games.',
      image: 'https://rare-gallery.com/thumbnail/394524-ai-gaming.jpg',
      status: 'View Report',
    },
  ],
  'Adi Shankara Institute of Engineering and Technology': [
    {
      title: 'VR Seminar',
      college: 'Adi Shankara Institute of Engineering and Technology',
      venuep1: 'MAIN',
      venuep2: 'HALL',
      date: '14/07/22',
      detail: 'Seminar on the future of virtual reality and its applications in gaming.',
      image: 'https://rare-gallery.com/thumbnail/394523-vr-gaming.jpg',
      status: 'View Report',
    },
    {
      title: 'AI in Games Workshop',
      college: 'Adi Shankara Institute of Engineering and Technology',
      venuep1: 'LAB',
      venuep2: '3',
      date: '18/07/22',
      detail: 'A hands-on workshop on implementing AI for NPC behavior in games.',
      image: 'https://rare-gallery.com/thumbnail/394524-ai-gaming.jpg',
      status: 'View Report',
    },
  ],
  'Mar Athanasius College of Engineering': [
    {
      title: 'VR Seminar',
      college: 'Mar Athanasius College of Engineering',
      venuep1: 'MAIN',
      venuep2: 'HALL',
      date: '14/07/22',
      detail: 'Seminar on the future of virtual reality and its applications in gaming.',
      image: 'https://rare-gallery.com/thumbnail/394523-vr-gaming.jpg',
      status: 'View Report',
    },
    {
      title: 'AI in Games Workshop',
      college: 'Mar Athanasius College of Engineering',
      venuep1: 'LAB',
      venuep2: '3',
      date: '18/07/22',
      detail: 'A hands-on workshop on implementing AI for NPC behavior in games.',
      image: 'https://rare-gallery.com/thumbnail/394524-ai-gaming.jpg',
      status: 'View Report',
    },
  ],
  'LBS Institute of Technology': [
    {
      title: 'VR Seminar',
      college: 'LBS Institute of Technology',
      venuep1: 'MAIN',
      venuep2: 'HALL',
      date: '14/07/22',
      detail: 'Seminar on the future of virtual reality and its applications in gaming.',
      image: 'https://rare-gallery.com/thumbnail/394523-vr-gaming.jpg',
      status: 'View Report',
    },
    {
      title: 'AI in Games Workshop',
      college: 'LBS Institute of Technology',
      venuep1: 'LAB',
      venuep2: '3',
      date: '18/07/22',
      detail: 'A hands-on workshop on implementing AI for NPC behavior in games.',
      image: 'https://rare-gallery.com/thumbnail/394524-ai-gaming.jpg',
      status: 'View Report',
    },
  ],
  'KMEA Engineering College': [
    {
      title: 'VR Seminar',
      college: 'KMEA Engineering College',
      venuep1: 'MAIN',
      venuep2: 'HALL',
      date: '14/07/22',
      detail: 'Seminar on the future of virtual reality and its applications in gaming.',
      image: 'https://rare-gallery.com/thumbnail/394523-vr-gaming.jpg',
      status: 'View Report',
    },
    {
      title: 'AI in Games Workshop',
      college: 'KMEA Engineering College',
      venuep1: 'LAB',
      venuep2: '3',
      date: '18/07/22',
      detail: 'A hands-on workshop on implementing AI for NPC behavior in games.',
      image: 'https://rare-gallery.com/thumbnail/394524-ai-gaming.jpg',
      status: 'View Report',
    },
  ],
  'Albertian Institute of Science & Technology': [
    {
      title: 'VR Seminar',
      college: 'Albertian Institute of Science & Technology',
      venuep1: 'MAIN',
      venuep2: 'HALL',
      date: '14/07/22',
      detail: 'Seminar on the future of virtual reality and its applications in gaming.',
      image: 'https://rare-gallery.com/thumbnail/394523-vr-gaming.jpg',
      status: 'View Report',
    },
    {
      title: 'AI in Games Workshop',
      college: 'Albertian Institute of Science & Technology',
      venuep1: 'LAB',
      venuep2: '3',
      date: '18/07/22',
      detail: 'A hands-on workshop on implementing AI for NPC behavior in games.',
      image: 'https://rare-gallery.com/thumbnail/394524-ai-gaming.jpg',
      status: 'View Report',
    },
  ],
  'Vishwajyothi College of Engineering and Technology': [
    {
      title: 'VR Seminar',
      college: 'Vishwajyothi College of Engineering and Technology',
      venuep1: 'MAIN',
      venuep2: 'HALL',
      date: '14/07/22',
      detail: 'Seminar on the future of virtual reality and its applications in gaming.',
      image: 'https://rare-gallery.com/thumbnail/394523-vr-gaming.jpg',
      status: 'View Report',
    },
    {
      title: 'AI in Games Workshop',
      college: 'Vishwajyothi College of Engineering and Technology',
      venuep1: 'LAB',
      venuep2: '3',
      date: '18/07/22',
      detail: 'A hands-on workshop on implementing AI for NPC behavior in games.',
      image: 'https://rare-gallery.com/thumbnail/394524-ai-gaming.jpg',
      status: 'View Report',
    },
  ],
  'Rajadhani Institute of Science & Technology': [
   /* {
      title: 'VR Seminar',
      college: 'Rajadhani Institute of Science & Technology',
      venuep1: 'MAIN',
      venuep2: 'HALL',
      date: '14/07/22',
      detail: 'Seminar on the future of virtual reality and its applications in gaming.',
      image: 'https://rare-gallery.com/thumbnail/394523-vr-gaming.jpg',
      status: 'View Report',
    },
    {
      title: 'AI in Games Workshop',
      college: 'Rajadhani Institute of Science & Technology',
      venuep1: 'LAB',
      venuep2: '3',
      date: '18/07/22',
      detail: 'A hands-on workshop on implementing AI for NPC behavior in games.',
      image: 'https://rare-gallery.com/thumbnail/394524-ai-gaming.jpg',
      status: 'View Report',
    },*/
  ],
};

export default pastEvents;
